/*******************************************************************************
* File Name: USBFS_descr.c
* Version 2.60
*
* Description:
*  USB descriptors and storage.
*
*  Note:
*
********************************************************************************
* Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions,
* disclaimers, and limitations in the end user license agreement accompanying
* the software package with which this file was provided.
*******************************************************************************/

#include "USBFS.h"
#include "USBFS_pvt.h"


/*****************************************************************************
*  User supplied descriptors.  If you want to specify your own descriptors,
*  remove the comments around the define USER_SUPPLIED_DESCRIPTORS below and
*  add your descriptors.
*****************************************************************************/
/* `#START USER_DESCRIPTORS_DECLARATIONS` Place your declaration here */
//#define USER_SUPPLIED_DESCRIPTORS

#ifdef USER_SUPPLIED_DESCRIPTORS
/* To the descriptor generated by the USBFS component, interface association descriptor is added for CDC interface */
/*********************************************************************
* Device Descriptors
*********************************************************************/
const uint8 CYCODE USBFS_DEVICE0_DESCR[] = {
/* Descriptor Length                       */ 0x12u,
/* DescriptorType: DEVICE                  */ 0x01u,
/* bcdUSB (ver 2.0)                        */ 0x00u, 0x02u,
/* bDeviceClass                            */ 0x00u,
/* bDeviceSubClass                         */ 0x00u,
/* bDeviceProtocol                         */ 0x00u,
/* bMaxPacketSize0                         */ 0x08u,
/* idVendor                                */ 0xB4u, 0x04u,
/* idProduct                               */ 0x02u, 0xE0u,
/* bcdDevice                               */ 0x00u, 0x40u,
/* iManufacturer                           */ 0x01u,
/* iProduct                                */ 0x00u,
/* iSerialNumber                           */ 0x80u,
/* bNumConfigurations                      */ 0x01u
};
/*********************************************************************
* Config Descriptor  
*********************************************************************/
const uint8 CYCODE USBFS_DEVICE0_CONFIGURATION0_DESCR[] = {
/*  Config Descriptor Length               */ 0x09u,
/*  DescriptorType: CONFIG                 */ 0x02u,
/*  wTotalLength                           */ 0x6Eu, 0x01u, /* KRIS Updates - Changed from 0x15E to 0x16E to add Interface Association Descriptor lengths */
/*  bNumInterfaces                         */ 0x06u,
/*  bConfigurationValue                    */ 0x01u,
/*  iConfiguration                         */ 0x0Au,
/*  bmAttributes                           */ 0xC0u,
/*  bMaxPower                              */ 0x00u,
/*********************************************************************
 Interface Association Descriptor - KRIS Updates
 *********************************************************************/
/*  Descriptor Length            	       */ 0x08u,
/*  DescriptorType: IAD              	   */ 0x0Bu,
/*  bFirstInterface                        */ 0x00u,
/*  bInterfaceCount                        */ 0x03u,
/*  bFunctionClass                         */ 0x01u,
/*  bFunctionSubClass :                	   */ 0x01u,
/*  bFunctionProtocol :           		   */ 0x00u,
/*  iFunction                              */ 0x00u,        
/*********************************************************************
* AudioControl Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x00u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x01u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Cu,
/*********************************************************************
* AC Header Descriptor
*********************************************************************/
/*  AC Header Descriptor Length            */ 0x0Au,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bcdADC                                 */ 0x00u, 0x01u,
/*  wTotalLength                           */ 0x44u, 0x00u,
/*  bInCollection                          */ 0x02u,
/*  baInterfaceNr                          */ 0x01u, 0x02u,
/*********************************************************************
* AC Feature Unit Descriptor
*********************************************************************/
/*  AC Feature Unit Descriptor Length      */ 0x08u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x06u,
/*  bUnitID                                */ 0x02u,
/*  bSourceID                              */ 0x01u,
/*  bControlSize                           */ 0x01u,
/*  bmaControls                            */ 0x03u,
/*  iFeature                               */ 0x00u,
/*********************************************************************
* AC Input Terminal Descriptor
*********************************************************************/
/*  AC Input Terminal Descriptor Length    */ 0x0Cu,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bTerminalID                            */ 0x01u,
/*  wTerminalType                          */ 0x01u, 0x01u,
/*  bAssocTerminal                         */ 0x00u,
/*  bNrChannels                            */ 0x02u,
/*  wChannelConfig                         */ 0x03u, 0x00u,
/*  iChannelNames                          */ 0x00u,
/*  iTerminal                              */ 0x07u,
/*********************************************************************
* AC Output Terminal Descriptor
*********************************************************************/
/*  AC Output Terminal Descriptor Length   */ 0x09u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x03u,
/*  bTerminalID                            */ 0x03u,
/*  wTerminalType                          */ 0x01u, 0x03u,
/*  bAssocTerminal                         */ 0x00u,
/*  bSourceID                              */ 0x02u,
/*  iTerminal                              */ 0x06u,
/*********************************************************************
* AC Input Terminal Descriptor
*********************************************************************/
/*  AC Input Terminal Descriptor Length    */ 0x0Cu,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bTerminalID                            */ 0x04u,
/*  wTerminalType                          */ 0x01u, 0x02u,
/*  bAssocTerminal                         */ 0x00u,
/*  bNrChannels                            */ 0x02u,
/*  wChannelConfig                         */ 0x03u, 0x00u,
/*  iChannelNames                          */ 0x00u,
/*  iTerminal                              */ 0x05u,
/*********************************************************************
* AC Output Terminal Descriptor
*********************************************************************/
/*  AC Output Terminal Descriptor Length   */ 0x09u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x03u,
/*  bTerminalID                            */ 0x05u,
/*  wTerminalType                          */ 0x01u, 0x01u,
/*  bAssocTerminal                         */ 0x00u,
/*  bSourceID                              */ 0x06u,
/*  iTerminal                              */ 0x07u,
/*********************************************************************
* AC Feature Unit Descriptor
*********************************************************************/
/*  AC Feature Unit Descriptor Length      */ 0x08u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x06u,
/*  bUnitID                                */ 0x06u,
/*  bSourceID                              */ 0x04u,
/*  bControlSize                           */ 0x01u,
/*  bmaControls                            */ 0x03u,
/*  iFeature                               */ 0x00u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x09u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x83u,
/*  bmAttributes                           */ 0x03u,
/*  wMaxPacketSize                         */ 0x02u, 0x00u,
/*  bInterval                              */ 0x1Eu,
/*  bRefresh                               */ 0x00u,
/*  bSynchAddress                          */ 0x00u,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x01u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x00u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Cu,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x01u,
/*  bAlternateSetting                      */ 0x01u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x08u,
/*********************************************************************
* AS General Descriptor
*********************************************************************/
/*  AS General Descriptor Length           */ 0x07u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bTerminalLink                          */ 0x01u,
/*  bDelay                                 */ 0x01u,
/*  wFormatTag                             */ 0x01u, 0x00u,
/*********************************************************************
* AS Format Type I Descriptor
*********************************************************************/
/*  AS Format Type I Descriptor Length     */ 0x11u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bFormatType                            */ 0x01u,
/*  bNrChannels                            */ 0x02u,
/*  bSubframeSize                          */ 0x02u,
/*  bBitResolution                         */ 0x10u,
/*  bSamFreqType                           */ 0x03u,
/*  tSamFreq                               */ 0x00u, 0x7Du, 0x00u, 
                                              0x44u, 0xACu, 0x00u, 
                                              0x80u, 0xBBu, 0x00u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x09u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x01u,
/*  bmAttributes                           */ 0x01u,
/*  wMaxPacketSize                         */ 0xC0u, 0x00u,
/*  bInterval                              */ 0x01u,
/*  bRefresh                               */ 0x00u,
/*  bSynchAddress                          */ 0x00u,
/*********************************************************************
* AS Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: CS_ENDPOINT            */ 0x25u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bmAttributes                           */ 0x01u,
/*  bLockDelayUnits                        */ 0x01u,
/*  wLockDelay                             */ 0x01u, 0x00u,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x01u,
/*  bAlternateSetting                      */ 0x02u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x09u,
/*********************************************************************
* AS General Descriptor
*********************************************************************/
/*  AS General Descriptor Length           */ 0x07u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bTerminalLink                          */ 0x01u,
/*  bDelay                                 */ 0x01u,
/*  wFormatTag                             */ 0x01u, 0x00u,
/*********************************************************************
* AS Format Type I Descriptor
*********************************************************************/
/*  AS Format Type I Descriptor Length     */ 0x11u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bFormatType                            */ 0x01u,
/*  bNrChannels                            */ 0x02u,
/*  bSubframeSize                          */ 0x03u,
/*  bBitResolution                         */ 0x18u,
/*  bSamFreqType                           */ 0x03u,
/*  tSamFreq                               */ 0x00u, 0x7Du, 0x00u, 
                                              0x44u, 0xACu, 0x00u, 
                                              0x80u, 0xBBu, 0x00u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x09u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x01u,
/*  bmAttributes                           */ 0x0Du,
/*  wMaxPacketSize                         */ 0x20u, 0x01u,
/*  bInterval                              */ 0x01u,
/*  bRefresh                               */ 0x00u,
/*  bSynchAddress                          */ 0x00u,
/*********************************************************************
* AS Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: CS_ENDPOINT            */ 0x25u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bmAttributes                           */ 0x01u,
/*  bLockDelayUnits                        */ 0x01u,
/*  wLockDelay                             */ 0x01u, 0x00u,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x02u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x00u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Cu,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x02u,
/*  bAlternateSetting                      */ 0x01u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x09u,
/*********************************************************************
* AS General Descriptor
*********************************************************************/
/*  AS General Descriptor Length           */ 0x07u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bTerminalLink                          */ 0x05u,
/*  bDelay                                 */ 0x01u,
/*  wFormatTag                             */ 0x01u, 0x00u,
/*********************************************************************
* AS Format Type I Descriptor
*********************************************************************/
/*  AS Format Type I Descriptor Length     */ 0x11u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bFormatType                            */ 0x01u,
/*  bNrChannels                            */ 0x02u,
/*  bSubframeSize                          */ 0x03u,
/*  bBitResolution                         */ 0x18u,
/*  bSamFreqType                           */ 0x03u,
/*  tSamFreq                               */ 0x00u, 0x7Du, 0x00u, 
                                              0x44u, 0xACu, 0x00u, 
                                              0x80u, 0xBBu, 0x00u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x09u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x82u,
/*  bmAttributes                           */ 0x0Du,
/*  wMaxPacketSize                         */ 0x20u, 0x01u,
/*  bInterval                              */ 0x01u,
/*  bRefresh                               */ 0x00u,
/*  bSynchAddress                          */ 0x00u,
/*********************************************************************
* AS Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: CS_ENDPOINT            */ 0x25u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bmAttributes                           */ 0x01u,
/*  bLockDelayUnits                        */ 0x01u,
/*  wLockDelay                             */ 0x01u, 0x00u,
/*********************************************************************
* Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x03u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x02u,
/*  bInterfaceClass                        */ 0x03u,
/*  bInterfaceSubClass                     */ 0x00u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Bu,
/*********************************************************************
* HID Class Descriptor
*********************************************************************/
/*  HID Class Descriptor Length            */ 0x09u,
/*  DescriptorType: HID_CLASS              */ 0x21u,
/*  bcdHID                                 */ 0x11u, 0x01u,
/*  bCountryCode                           */ 0x00u,
/*  bNumDescriptors                        */ 0x01u,
/*  bDescriptorType                        */ 0x22u,
/*  wDescriptorLength (LSB)                */ USBFS_HID_RPT_1_SIZE_LSB,
/*  wDescriptorLength (MSB)                */ USBFS_HID_RPT_1_SIZE_MSB,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x84u,
/*  bmAttributes                           */ 0x03u,
/*  wMaxPacketSize                         */ 0x02u, 0x00u,
/*  bInterval                              */ 0x28u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x05u,
/*  bmAttributes                           */ 0x03u,
/*  wMaxPacketSize                         */ 0x01u, 0x00u,
/*  bInterval                              */ 0x0Au,
/*********************************************************************
 Interface Association Descriptor - KRIS Updates
 *********************************************************************/
/*  Descriptor Length            	       */ 0x08u,
/*  DescriptorType: IAD              	   */ 0x0Bu,
/*  bFirstInterface                        */ 0x04u,
/*  bInterfaceCount                        */ 0x02u,
/*  bFunctionClass                         */ 0x02u,
/*  bFunctionSubClass :                	   */ 0x00u,
/*  bFunctionProtocol :           		   */ 0x00u,
/*  iFunction                              */ 0x00u,    
/*********************************************************************
* CDC Interface Descriptor 
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x04u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x02u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Eu,
/*********************************************************************
* Header Descriptor
*********************************************************************/
/*  Header Descriptor Length               */ 0x05u,
/*  DescriptorType: CS_INTERFACE           */ 0x24u,
/*  bDescriptorSubtype                     */ 0x00u,
/*  bcdADC                                 */ 0x10u, 0x01u,
/*********************************************************************
* Abstract Control Management Descriptor
*********************************************************************/
/*  Abstract Control Management Descriptor Length*/ 0x04u,
/*  DescriptorType: CS_INTERFACE           */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bmCapabilities                         */ 0x02u,
/*********************************************************************
* Union Descriptor
*********************************************************************/
/*  Union Descriptor Length                */ 0x05u,
/*  DescriptorType: CS_INTERFACE           */ 0x24u,
/*  bDescriptorSubtype                     */ 0x06u,
/*  bControlInterface                      */ 0x04u,
/*  bSubordinateInterface                  */ 0x05u,
/*********************************************************************
* Call Management Descriptor
*********************************************************************/
/*  Call Management Descriptor Length      */ 0x05u,
/*  DescriptorType: CS_INTERFACE           */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bmCapabilities                         */ 0x00u,
/*  bDataInterface                         */ 0x05u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x86u,
/*  bmAttributes                           */ 0x03u,
/*  wMaxPacketSize                         */ 0x08u, 0x00u,
/*  bInterval                              */ 0x0Au,
/*********************************************************************
* Data Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x05u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x02u,
/*  bInterfaceClass                        */ 0x0Au,
/*  bInterfaceSubClass                     */ 0x00u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Fu,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x87u,
/*  bmAttributes                           */ 0x02u,
/*  wMaxPacketSize                         */ 0x40u, 0x00u,
/*  bInterval                              */ 0x0Au,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x08u,
/*  bmAttributes                           */ 0x02u,
/*  wMaxPacketSize                         */ 0x40u, 0x00u,
/*  bInterval                              */ 0x0Au
};

/*********************************************************************
* String Descriptor Table
*********************************************************************/
const uint8 CYCODE USBFS_STRING_DESCRIPTORS[] = {
/*********************************************************************
* Language ID Descriptor
*********************************************************************/
/* Descriptor Length                       */ 0x04u,
/* DescriptorType: STRING                  */ 0x03u,
/* Language Id                             */ 0x09u, 0x04u,
/*********************************************************************
* String Descriptor: "Cypress Semiconductor"
*********************************************************************/
/* Descriptor Length                       */ 0x2Cu,
/* DescriptorType: STRING                  */ 0x03u,
 'C', 0,'y', 0,'p', 0,'r', 0,'e', 0,'s', 0,'s', 0,' ', 0,'S', 0,'e', 0
,'m', 0,'i', 0,'c', 0,'o', 0,'n', 0,'d', 0,'u', 0,'c', 0,'t', 0,'o', 0
,'r', 0,
/*********************************************************************
* String Descriptor: "iAP Interface"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 'i', 0,'A', 0,'P', 0,' ', 0,'I', 0,'n', 0,'t', 0,'e', 0,'r', 0,'f', 0
,'a', 0,'c', 0,'e', 0,
/*********************************************************************
* String Descriptor: "ZeroBandwidth"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 'Z', 0,'e', 0,'r', 0,'o', 0,'B', 0,'a', 0,'n', 0,'d', 0,'w', 0,'i', 0
,'d', 0,'t', 0,'h', 0,
/*********************************************************************
* String Descriptor: "iOS Host"
*********************************************************************/
/* Descriptor Length                       */ 0x12u,
/* DescriptorType: STRING                  */ 0x03u,
 'i', 0,'O', 0,'S', 0,' ', 0,'H', 0,'o', 0,'s', 0,'t', 0,
/*********************************************************************
* String Descriptor: "Microphone"
*********************************************************************/
/* Descriptor Length                       */ 0x16u,
/* DescriptorType: STRING                  */ 0x03u,
 'M', 0,'i', 0,'c', 0,'r', 0,'o', 0,'p', 0,'h', 0,'o', 0,'n', 0,'e', 0,
/*********************************************************************
* String Descriptor: "Speaker"
*********************************************************************/
/* Descriptor Length                       */ 0x10u,
/* DescriptorType: STRING                  */ 0x03u,
 'S', 0,'p', 0,'e', 0,'a', 0,'k', 0,'e', 0,'r', 0,
/*********************************************************************
* String Descriptor: "USB Streaming"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 'U', 0,'S', 0,'B', 0,' ', 0,'S', 0,'t', 0,'r', 0,'e', 0,'a', 0,'m', 0
,'i', 0,'n', 0,'g', 0,
/*********************************************************************
* String Descriptor: "Active 16 bit"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 'A', 0,'c', 0,'t', 0,'i', 0,'v', 0,'e', 0,' ', 0,'1', 0,'6', 0,' ', 0
,'b', 0,'i', 0,'t', 0,
/*********************************************************************
* String Descriptor: "Active 24 bit"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 'A', 0,'c', 0,'t', 0,'i', 0,'v', 0,'e', 0,' ', 0,'2', 0,'4', 0,' ', 0
,'b', 0,'i', 0,'t', 0,
/*********************************************************************
* String Descriptor: "Mac"
*********************************************************************/
/* Descriptor Length                       */ 0x08u,
/* DescriptorType: STRING                  */ 0x03u,
 'M', 0,'a', 0,'c', 0,
/*********************************************************************
* String Descriptor: "PlaylistControl"
*********************************************************************/
/* Descriptor Length                       */ 0x20u,
/* DescriptorType: STRING                  */ 0x03u,
 'P', 0,'l', 0,'a', 0,'y', 0,'l', 0,'i', 0,'s', 0,'t', 0,'C', 0,'o', 0
,'n', 0,'t', 0,'r', 0,'o', 0,'l', 0,
/*********************************************************************
* String Descriptor: "Cypress MFi Digital Audio DVK"
*********************************************************************/
/* Descriptor Length                       */ 0x3Cu,
/* DescriptorType: STRING                  */ 0x03u,
 'C', 0,'y', 0,'p', 0,'r', 0,'e', 0,'s', 0,'s', 0,' ', 0,'M', 0,'F', 0
,'i', 0,' ', 0,'D', 0,'i', 0,'g', 0,'i', 0,'t', 0,'a', 0,'l', 0,' ', 0
,'A', 0,'u', 0,'d', 0,'i', 0,'o', 0,' ', 0,'D', 0,'V', 0,'K', 0,
/*********************************************************************
* String Descriptor: "Audio Control"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 'A', 0,'u', 0,'d', 0,'i', 0,'o', 0,' ', 0,'C', 0,'o', 0,'n', 0,'t', 0
,'r', 0,'o', 0,'l', 0,
/*********************************************************************
* String Descriptor: "CDC Communication Interface"
*********************************************************************/
/* Descriptor Length                       */ 0x38u,
/* DescriptorType: STRING                  */ 0x03u,
 'C', 0,'D', 0,'C', 0,' ', 0,'C', 0,'o', 0,'m', 0,'m', 0,'u', 0,'n', 0
,'i', 0,'c', 0,'a', 0,'t', 0,'i', 0,'o', 0,'n', 0,' ', 0,'I', 0,'n', 0
,'t', 0,'e', 0,'r', 0,'f', 0,'a', 0,'c', 0,'e', 0,
/*********************************************************************
* String Descriptor: "CDC Data Interface"
*********************************************************************/
/* Descriptor Length                       */ 0x26u,
/* DescriptorType: STRING                  */ 0x03u,
 'C', 0,'D', 0,'C', 0,' ', 0,'D', 0,'a', 0,'t', 0,'a', 0,' ', 0,'I', 0
,'n', 0,'t', 0,'e', 0,'r', 0,'f', 0,'a', 0,'c', 0,'e', 0,
/*********************************************************************/
/* Marks the end of the list.              */ 0x00u};
/*********************************************************************/

/*********************************************************************
* Serial Number String Descriptor
*********************************************************************/
const uint8 CYCODE USBFS_SN_STRING_DESCRIPTOR[] = {
/* Descriptor Length                       */ 0x02u,
/* DescriptorType: STRING                  */ 0x03u
};

/*********************************************************************
* HID Report Descriptor: AudioPlaybackControl
*********************************************************************/
const uint8 CYCODE USBFS_HIDREPORT_DESCRIPTOR1[] = {
/*  Descriptor Size (Not part of descriptor)*/ USBFS_HID_RPT_1_SIZE_LSB,
USBFS_HID_RPT_1_SIZE_MSB,
/* USAGE_PAGE                              */ 0x05u, 0x0Cu, 
/* USAGE                                   */ 0x09u, 0x01u, 
/* COLLECTION                              */ 0xA1u, 0x01u, 
/* REPORT_ID                               */ 0x85u, 0x01u, 
/* LOGICAL_MINIMUM                         */ 0x15u, 0x00u, 
/* LOGICAL_MAXIMUM                         */ 0x25u, 0x01u, 
/* REPORT_SIZE                             */ 0x75u, 0x01u, 
/* REPORT_COUNT                            */ 0x95u, 0x03u, 
/* USAGE                                   */ 0x09u, 0xCDu, 
/* USAGE                                   */ 0x09u, 0xB5u, 
/* USAGE                                   */ 0x09u, 0xB6u, 
/* INPUT                                   */ 0x81u, 0x02u, 
/* REPORT_COUNT                            */ 0x95u, 0x05u, 
/* INPUT                                   */ 0x81u, 0x01u, 
/* END_COLLECTION                          */ 0xC0u, 
/* USAGE_PAGE                              */ 0x05u, 0x0Bu, 
/* USAGE                                   */ 0x09u, 0x01u, 
/* COLLECTION                              */ 0xA1u, 0x01u, 
/* REPORT_ID                               */ 0x85u, 0x02u, 
/* LOGICAL_MINIMUM                         */ 0x15u, 0x00u, 
/* LOGICAL_MAXIMUM                         */ 0x25u, 0x01u, 
/* REPORT_SIZE                             */ 0x75u, 0x01u, 
/* REPORT_COUNT                            */ 0x95u, 0x02u, 
/* USAGE                                   */ 0x09u, 0x26u, 
/* USAGE                                   */ 0x09u, 0x2Fu, 
/* INPUT                                   */ 0x81u, 0x02u, 
/* REPORT_COUNT                            */ 0x95u, 0x06u, 
/* INPUT                                   */ 0x81u, 0x01u, 
/* END_COLLECTION                          */ 0xC0u, 
/* USAGE_PAGE                              */ 0x05u, 0x0Bu, 
/* USAGE                                   */ 0x09u, 0x01u, 
/* COLLECTION                              */ 0xA1u, 0x01u, 
/* REPORT_ID                               */ 0x85u, 0x03u, 
/* LOGICAL_MINIMUM                         */ 0x15u, 0x00u, 
/* LOGICAL_MAXIMUM                         */ 0x25u, 0x01u, 
/* REPORT_SIZE                             */ 0x75u, 0x01u, 
/* REPORT_COUNT                            */ 0x95u, 0x08u, 
/* USAGE                                   */ 0x09u, 0x26u, 
/* USAGE                                   */ 0x09u, 0x2Fu, 
/* USAGE                                   */ 0x09u, 0xB0u, 
/* USAGE                                   */ 0x09u, 0xB1u, 
/* USAGE                                   */ 0x09u, 0xB2u, 
/* USAGE                                   */ 0x09u, 0xB3u, 
/* USAGE                                   */ 0x09u, 0xB4u, 
/* USAGE                                   */ 0x09u, 0xB5u, 
/* OUTPUT                                  */ 0x91u, 0x02u, 
/* END_COLLECTION                          */ 0xC0u, 
/*********************************************************************/
/* End of the HID Report Descriptor        */ 0x00u, 0x00u};
/*********************************************************************/

#if !defined(USER_DEFINE_USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_HID_RPT_STORAGE)
/*********************************************************************
* HID Input Report Storage
*********************************************************************/
T_USBFS_XFER_STATUS_BLOCK USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_RPT_SCB_ID1;
uint8 USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_BUF_ID1[
            USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_BUF_SIZE_ID1];

T_USBFS_XFER_STATUS_BLOCK USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_RPT_SCB_ID2;
uint8 USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_BUF_ID2[
            USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_BUF_SIZE_ID2];

/*********************************************************************
* HID Input Report TD Table
*********************************************************************/
const T_USBFS_TD CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_RPT_TABLE[] = {
    {NULL,
    NULL,
    NULL},
    {USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_BUF_SIZE_ID1,
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_BUF_ID1[0],
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_RPT_SCB_ID1},
    {USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_BUF_SIZE_ID2,
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_BUF_ID2[0],
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_RPT_SCB_ID2},
};
/*********************************************************************
* HID Output Report Storage
*********************************************************************/
T_USBFS_XFER_STATUS_BLOCK USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_OUT_RPT_SCB_ID3;
uint8 USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_OUT_BUF_ID3[
            USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_OUT_BUF_SIZE_ID3];

/*********************************************************************
* HID Output Report TD Table
*********************************************************************/
const T_USBFS_TD CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_OUT_RPT_TABLE[] = {
    {NULL,
    NULL,
    NULL},
    {NULL,
    NULL,
    NULL},
    {NULL,
    NULL,
    NULL},
    {USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_OUT_BUF_SIZE_ID3,
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_OUT_BUF_ID3[0],
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_OUT_RPT_SCB_ID3},
};
/*********************************************************************
* HID Report Look Up Table         This table has four entries:
*                                        IN Report Table
*                                        OUT Report Table
*                                        Feature Report Table
*                                        HID Report Descriptor
*                                        HID Class Descriptor
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_TABLE[] = {
    {0x02u,     &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_IN_RPT_TABLE},
    {0x03u,     &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_OUT_RPT_TABLE},
    {0x00u,    NULL},
    {0x01u,     (void *)&USBFS_HIDREPORT_DESCRIPTOR1[0]},
    {0x01u,     (void *)&USBFS_DEVICE0_CONFIGURATION0_DESCR[269]}
};
#endif /* USER_DEFINE_USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_HID_RPT_STORAGE */

/*********************************************************************
* Interface Dispatch Table -- Points to the Class Dispatch Tables
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_TABLE[] = {
    {USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_COUNT, 
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_ALTERNATE0_HID_TABLE}
};
/*********************************************************************
* Endpoint Setting Table -- This table contain the endpoint setting
*                           for each endpoint in the configuration. It
*                           contains the necessary information to
*                           configure the endpoint hardware for each
*                           interface and alternate setting.
*********************************************************************/
const T_USBFS_EP_SETTINGS_BLOCK CYCODE USBFS_DEVICE0_CONFIGURATION0_EP_SETTINGS_TABLE[] = {
/* IFC  ALT    EPAddr bmAttr MaxPktSize Class ********************/
{0x00u, 0x00u, 0x83u, 0x03u, 0x0002u,   0x01u},
{0x01u, 0x01u, 0x01u, 0x01u, 0x00C0u,   0x01u},
{0x01u, 0x02u, 0x01u, 0x0Du, 0x0120u,   0x01u},
{0x02u, 0x01u, 0x82u, 0x0Du, 0x0120u,   0x01u},
{0x03u, 0x00u, 0x84u, 0x03u, 0x0002u,   0x03u},
{0x03u, 0x00u, 0x05u, 0x03u, 0x0001u,   0x03u},
{0x04u, 0x00u, 0x86u, 0x03u, 0x0008u,   0x02u},
{0x05u, 0x00u, 0x87u, 0x02u, 0x0040u,   0x0Au},
{0x05u, 0x00u, 0x08u, 0x02u, 0x0040u,   0x0Au}
};
const uint8 CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE_CLASS[] = {
0x01u, 0x01u, 0x01u, 0x03u, 0x02u, 0x0Au
};
/*********************************************************************
* Config Dispatch Table -- Points to the Config Descriptor and each of
*                          and endpoint setup table and to each
*                          interface table if it specifies a USB Class
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_DEVICE0_CONFIGURATION0_TABLE[] = {
    {0x01u,     &USBFS_DEVICE0_CONFIGURATION0_DESCR},
    {0x09u,     &USBFS_DEVICE0_CONFIGURATION0_EP_SETTINGS_TABLE},
    {0x00u,    NULL},
    {0x00u,    NULL},
    {0x00u,    NULL},
    {0x01u,     &USBFS_DEVICE0_CONFIGURATION0_INTERFACE3_TABLE},
    {0x00u,    NULL},
    {0x00u,    NULL},
    {0x00u,     &USBFS_DEVICE0_CONFIGURATION0_INTERFACE_CLASS}
};
/*********************************************************************
* Device Dispatch Table -- Points to the Device Descriptor and each of
*                          and Configuration Tables for this Device 
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_DEVICE0_TABLE[] = {
    {0x01u,     &USBFS_DEVICE0_DESCR},
    {0x01u,     &USBFS_DEVICE0_CONFIGURATION0_TABLE}
};
/*********************************************************************
* Device Table -- Indexed by the device number.
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_TABLE[] = {
    {0x01u,     &USBFS_DEVICE0_TABLE}
};
#endif

/* `#END` */


/***************************************
*  USB Customizer Generated Descriptors
***************************************/

#if !defined(USER_SUPPLIED_DESCRIPTORS)
/*********************************************************************
* Device Descriptors
*********************************************************************/
const uint8 CYCODE USBFS_DEVICE0_DESCR[18u] = {
/* Descriptor Length                       */ 0x12u,
/* DescriptorType: DEVICE                  */ 0x01u,
/* bcdUSB (ver 2.0)                        */ 0x00u, 0x02u,
/* bDeviceClass                            */ 0x00u,
/* bDeviceSubClass                         */ 0x00u,
/* bDeviceProtocol                         */ 0x00u,
/* bMaxPacketSize0                         */ 0x08u,
/* idVendor                                */ 0xB4u, 0x04u,
/* idProduct                               */ 0x02u, 0xE0u,
/* bcdDevice                               */ 0x00u, 0x40u,
/* iManufacturer                           */ 0x01u,
/* iProduct                                */ 0x00u,
/* iSerialNumber                           */ 0x80u,
/* bNumConfigurations                      */ 0x01u
};
/*********************************************************************
* Config Descriptor  
*********************************************************************/
const uint8 CYCODE USBFS_DEVICE0_CONFIGURATION0_DESCR[366u] = {
/*  Config Descriptor Length               */ 0x09u,
/*  DescriptorType: CONFIG                 */ 0x02u,
/*  wTotalLength                           */ 0x6Eu, 0x01u,
/*  bNumInterfaces                         */ 0x06u,
/*  bConfigurationValue                    */ 0x01u,
/*  iConfiguration                         */ 0x0Au,
/*  bmAttributes                           */ 0xC0u,
/*  bMaxPower                              */ 0x00u,
/*********************************************************************
* Interface Association Descriptor
*********************************************************************/
/*  Interface Association Descriptor Length*/ 0x08u,
/*  DescriptorType: INTERFACE ASSOCIATION  */ 0x0Bu,
/*  bFirstInterface                        */ 0x00u,
/*  bInterfaceCount                        */ 0x03u,
/*  bFunctionClass                         */ 0x01u,
/*  bFunctionSubClass                      */ 0x01u,
/*  bFunctionProtocol                      */ 0x00u,
/*  iFunction                              */ 0x00u,
/*********************************************************************
* AudioControl Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x00u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x01u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Cu,
/*********************************************************************
* AC Header Descriptor
*********************************************************************/
/*  AC Header Descriptor Length            */ 0x0Au,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bcdADC                                 */ 0x00u, 0x01u,
/*  wTotalLength                           */ 0x44u, 0x00u,
/*  bInCollection                          */ 0x02u,
/*  baInterfaceNr                          */ 0x01u, 0x02u,
/*********************************************************************
* AC Feature Unit Descriptor
*********************************************************************/
/*  AC Feature Unit Descriptor Length      */ 0x08u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x06u,
/*  bUnitID                                */ 0x02u,
/*  bSourceID                              */ 0x01u,
/*  bControlSize                           */ 0x01u,
/*  bmaControls                            */ 0x03u,
/*  iFeature                               */ 0x00u,
/*********************************************************************
* AC Input Terminal Descriptor
*********************************************************************/
/*  AC Input Terminal Descriptor Length    */ 0x0Cu,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bTerminalID                            */ 0x01u,
/*  wTerminalType                          */ 0x01u, 0x01u,
/*  bAssocTerminal                         */ 0x00u,
/*  bNrChannels                            */ 0x02u,
/*  wChannelConfig                         */ 0x03u, 0x00u,
/*  iChannelNames                          */ 0x00u,
/*  iTerminal                              */ 0x07u,
/*********************************************************************
* AC Output Terminal Descriptor
*********************************************************************/
/*  AC Output Terminal Descriptor Length   */ 0x09u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x03u,
/*  bTerminalID                            */ 0x03u,
/*  wTerminalType                          */ 0x01u, 0x03u,
/*  bAssocTerminal                         */ 0x00u,
/*  bSourceID                              */ 0x02u,
/*  iTerminal                              */ 0x06u,
/*********************************************************************
* AC Input Terminal Descriptor
*********************************************************************/
/*  AC Input Terminal Descriptor Length    */ 0x0Cu,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bTerminalID                            */ 0x04u,
/*  wTerminalType                          */ 0x01u, 0x02u,
/*  bAssocTerminal                         */ 0x00u,
/*  bNrChannels                            */ 0x02u,
/*  wChannelConfig                         */ 0x03u, 0x00u,
/*  iChannelNames                          */ 0x00u,
/*  iTerminal                              */ 0x05u,
/*********************************************************************
* AC Output Terminal Descriptor
*********************************************************************/
/*  AC Output Terminal Descriptor Length   */ 0x09u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x03u,
/*  bTerminalID                            */ 0x05u,
/*  wTerminalType                          */ 0x01u, 0x01u,
/*  bAssocTerminal                         */ 0x00u,
/*  bSourceID                              */ 0x06u,
/*  iTerminal                              */ 0x07u,
/*********************************************************************
* AC Feature Unit Descriptor
*********************************************************************/
/*  AC Feature Unit Descriptor Length      */ 0x08u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x06u,
/*  bUnitID                                */ 0x06u,
/*  bSourceID                              */ 0x04u,
/*  bControlSize                           */ 0x01u,
/*  bmaControls                            */ 0x03u,
/*  iFeature                               */ 0x00u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x09u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x83u,
/*  bmAttributes                           */ 0x03u,
/*  wMaxPacketSize                         */ 0x02u, 0x00u,
/*  bInterval                              */ 0x1Eu,
/*  bRefresh                               */ 0x00u,
/*  bSynchAddress                          */ 0x00u,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x01u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x00u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Cu,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x01u,
/*  bAlternateSetting                      */ 0x01u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x08u,
/*********************************************************************
* AS General Descriptor
*********************************************************************/
/*  AS General Descriptor Length           */ 0x07u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bTerminalLink                          */ 0x01u,
/*  bDelay                                 */ 0x01u,
/*  wFormatTag                             */ 0x01u, 0x00u,
/*********************************************************************
* AS Format Type I Descriptor
*********************************************************************/
/*  AS Format Type I Descriptor Length     */ 0x11u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bFormatType                            */ 0x01u,
/*  bNrChannels                            */ 0x02u,
/*  bSubframeSize                          */ 0x02u,
/*  bBitResolution                         */ 0x10u,
/*  bSamFreqType                           */ 0x03u,
/*  tSamFreq                               */ 0x00u, 0x7Du, 0x00u, 
                                              0x44u, 0xACu, 0x00u, 
                                              0x80u, 0xBBu, 0x00u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x09u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x01u,
/*  bmAttributes                           */ 0x01u,
/*  wMaxPacketSize                         */ 0xC0u, 0x00u,
/*  bInterval                              */ 0x01u,
/*  bRefresh                               */ 0x00u,
/*  bSynchAddress                          */ 0x00u,
/*********************************************************************
* AS Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: CS_ENDPOINT            */ 0x25u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bmAttributes                           */ 0x01u,
/*  bLockDelayUnits                        */ 0x01u,
/*  wLockDelay                             */ 0x01u, 0x00u,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x01u,
/*  bAlternateSetting                      */ 0x02u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x09u,
/*********************************************************************
* AS General Descriptor
*********************************************************************/
/*  AS General Descriptor Length           */ 0x07u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bTerminalLink                          */ 0x01u,
/*  bDelay                                 */ 0x01u,
/*  wFormatTag                             */ 0x01u, 0x00u,
/*********************************************************************
* AS Format Type I Descriptor
*********************************************************************/
/*  AS Format Type I Descriptor Length     */ 0x11u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bFormatType                            */ 0x01u,
/*  bNrChannels                            */ 0x02u,
/*  bSubframeSize                          */ 0x03u,
/*  bBitResolution                         */ 0x18u,
/*  bSamFreqType                           */ 0x03u,
/*  tSamFreq                               */ 0x00u, 0x7Du, 0x00u, 
                                              0x44u, 0xACu, 0x00u, 
                                              0x80u, 0xBBu, 0x00u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x09u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x01u,
/*  bmAttributes                           */ 0x0Du,
/*  wMaxPacketSize                         */ 0x20u, 0x01u,
/*  bInterval                              */ 0x01u,
/*  bRefresh                               */ 0x00u,
/*  bSynchAddress                          */ 0x00u,
/*********************************************************************
* AS Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: CS_ENDPOINT            */ 0x25u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bmAttributes                           */ 0x01u,
/*  bLockDelayUnits                        */ 0x01u,
/*  wLockDelay                             */ 0x01u, 0x00u,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x02u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x00u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Cu,
/*********************************************************************
* AudioStreaming Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x02u,
/*  bAlternateSetting                      */ 0x01u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x01u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x09u,
/*********************************************************************
* AS General Descriptor
*********************************************************************/
/*  AS General Descriptor Length           */ 0x07u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bTerminalLink                          */ 0x05u,
/*  bDelay                                 */ 0x01u,
/*  wFormatTag                             */ 0x01u, 0x00u,
/*********************************************************************
* AS Format Type I Descriptor
*********************************************************************/
/*  AS Format Type I Descriptor Length     */ 0x11u,
/*  DescriptorType: AUDIO                  */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bFormatType                            */ 0x01u,
/*  bNrChannels                            */ 0x02u,
/*  bSubframeSize                          */ 0x03u,
/*  bBitResolution                         */ 0x18u,
/*  bSamFreqType                           */ 0x03u,
/*  tSamFreq                               */ 0x00u, 0x7Du, 0x00u, 
                                              0x44u, 0xACu, 0x00u, 
                                              0x80u, 0xBBu, 0x00u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x09u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x82u,
/*  bmAttributes                           */ 0x0Du,
/*  wMaxPacketSize                         */ 0x20u, 0x01u,
/*  bInterval                              */ 0x01u,
/*  bRefresh                               */ 0x00u,
/*  bSynchAddress                          */ 0x00u,
/*********************************************************************
* AS Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: CS_ENDPOINT            */ 0x25u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bmAttributes                           */ 0x01u,
/*  bLockDelayUnits                        */ 0x01u,
/*  wLockDelay                             */ 0x01u, 0x00u,
/*********************************************************************
* Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x03u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x02u,
/*  bInterfaceClass                        */ 0x03u,
/*  bInterfaceSubClass                     */ 0x00u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Bu,
/*********************************************************************
* HID Class Descriptor
*********************************************************************/
/*  HID Class Descriptor Length            */ 0x09u,
/*  DescriptorType: HID_CLASS              */ 0x21u,
/*  bcdHID                                 */ 0x11u, 0x01u,
/*  bCountryCode                           */ 0x00u,
/*  bNumDescriptors                        */ 0x01u,
/*  bDescriptorType                        */ 0x22u,
/*  wDescriptorLength (LSB)                */ USBFS_HID_RPT_1_SIZE_LSB,
/*  wDescriptorLength (MSB)                */ USBFS_HID_RPT_1_SIZE_MSB,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x84u,
/*  bmAttributes                           */ 0x03u,
/*  wMaxPacketSize                         */ 0x02u, 0x00u,
/*  bInterval                              */ 0x28u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x05u,
/*  bmAttributes                           */ 0x03u,
/*  wMaxPacketSize                         */ 0x01u, 0x00u,
/*  bInterval                              */ 0x0Au,
/*********************************************************************
* Interface Association Descriptor
*********************************************************************/
/*  Interface Association Descriptor Length*/ 0x08u,
/*  DescriptorType: INTERFACE ASSOCIATION  */ 0x0Bu,
/*  bFirstInterface                        */ 0x04u,
/*  bInterfaceCount                        */ 0x02u,
/*  bFunctionClass                         */ 0x02u,
/*  bFunctionSubClass                      */ 0x00u,
/*  bFunctionProtocol                      */ 0x00u,
/*  iFunction                              */ 0x00u,
/*********************************************************************
* CDC Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x04u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x01u,
/*  bInterfaceClass                        */ 0x02u,
/*  bInterfaceSubClass                     */ 0x02u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Eu,
/*********************************************************************
* Header Descriptor
*********************************************************************/
/*  Header Descriptor Length               */ 0x05u,
/*  DescriptorType: CS_INTERFACE           */ 0x24u,
/*  bDescriptorSubtype                     */ 0x00u,
/*  bcdADC                                 */ 0x10u, 0x01u,
/*********************************************************************
* Abstract Control Management Descriptor
*********************************************************************/
/*  Abstract Control Management Descriptor Length*/ 0x04u,
/*  DescriptorType: CS_INTERFACE           */ 0x24u,
/*  bDescriptorSubtype                     */ 0x02u,
/*  bmCapabilities                         */ 0x02u,
/*********************************************************************
* Union Descriptor
*********************************************************************/
/*  Union Descriptor Length                */ 0x05u,
/*  DescriptorType: CS_INTERFACE           */ 0x24u,
/*  bDescriptorSubtype                     */ 0x06u,
/*  bControlInterface                      */ 0x04u,
/*  bSubordinateInterface                  */ 0x05u,
/*********************************************************************
* Call Management Descriptor
*********************************************************************/
/*  Call Management Descriptor Length      */ 0x05u,
/*  DescriptorType: CS_INTERFACE           */ 0x24u,
/*  bDescriptorSubtype                     */ 0x01u,
/*  bmCapabilities                         */ 0x00u,
/*  bDataInterface                         */ 0x05u,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x86u,
/*  bmAttributes                           */ 0x03u,
/*  wMaxPacketSize                         */ 0x08u, 0x00u,
/*  bInterval                              */ 0x0Au,
/*********************************************************************
* Data Interface Descriptor
*********************************************************************/
/*  Interface Descriptor Length            */ 0x09u,
/*  DescriptorType: INTERFACE              */ 0x04u,
/*  bInterfaceNumber                       */ 0x05u,
/*  bAlternateSetting                      */ 0x00u,
/*  bNumEndpoints                          */ 0x02u,
/*  bInterfaceClass                        */ 0x0Au,
/*  bInterfaceSubClass                     */ 0x00u,
/*  bInterfaceProtocol                     */ 0x00u,
/*  iInterface                             */ 0x0Fu,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x87u,
/*  bmAttributes                           */ 0x02u,
/*  wMaxPacketSize                         */ 0x40u, 0x00u,
/*  bInterval                              */ 0x0Au,
/*********************************************************************
* Endpoint Descriptor
*********************************************************************/
/*  Endpoint Descriptor Length             */ 0x07u,
/*  DescriptorType: ENDPOINT               */ 0x05u,
/*  bEndpointAddress                       */ 0x08u,
/*  bmAttributes                           */ 0x02u,
/*  wMaxPacketSize                         */ 0x40u, 0x00u,
/*  bInterval                              */ 0x0Au
};

/*********************************************************************
* String Descriptor Table
*********************************************************************/
const uint8 CYCODE USBFS_STRING_DESCRIPTORS[467u] = {
/*********************************************************************
* Language ID Descriptor
*********************************************************************/
/* Descriptor Length                       */ 0x04u,
/* DescriptorType: STRING                  */ 0x03u,
/* Language Id                             */ 0x09u, 0x04u,
/*********************************************************************
* String Descriptor: "Cypress Semiconductor"
*********************************************************************/
/* Descriptor Length                       */ 0x2Cu,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'C', 0u,(uint8)'y', 0u,(uint8)'p', 0u,(uint8)'r', 0u,(uint8)'e', 0u,
 (uint8)'s', 0u,(uint8)'s', 0u,(uint8)' ', 0u,(uint8)'S', 0u,(uint8)'e', 0u,
 (uint8)'m', 0u,(uint8)'i', 0u,(uint8)'c', 0u,(uint8)'o', 0u,(uint8)'n', 0u,
 (uint8)'d', 0u,(uint8)'u', 0u,(uint8)'c', 0u,(uint8)'t', 0u,(uint8)'o', 0u,
 (uint8)'r', 0u,
/*********************************************************************
* String Descriptor: "iAP Interface"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'i', 0u,(uint8)'A', 0u,(uint8)'P', 0u,(uint8)' ', 0u,(uint8)'I', 0u,
 (uint8)'n', 0u,(uint8)'t', 0u,(uint8)'e', 0u,(uint8)'r', 0u,(uint8)'f', 0u,
 (uint8)'a', 0u,(uint8)'c', 0u,(uint8)'e', 0u,
/*********************************************************************
* String Descriptor: "ZeroBandwidth"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'Z', 0u,(uint8)'e', 0u,(uint8)'r', 0u,(uint8)'o', 0u,(uint8)'B', 0u,
 (uint8)'a', 0u,(uint8)'n', 0u,(uint8)'d', 0u,(uint8)'w', 0u,(uint8)'i', 0u,
 (uint8)'d', 0u,(uint8)'t', 0u,(uint8)'h', 0u,
/*********************************************************************
* String Descriptor: "iOS Host"
*********************************************************************/
/* Descriptor Length                       */ 0x12u,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'i', 0u,(uint8)'O', 0u,(uint8)'S', 0u,(uint8)' ', 0u,(uint8)'H', 0u,
 (uint8)'o', 0u,(uint8)'s', 0u,(uint8)'t', 0u,
/*********************************************************************
* String Descriptor: "Microphone"
*********************************************************************/
/* Descriptor Length                       */ 0x16u,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'M', 0u,(uint8)'i', 0u,(uint8)'c', 0u,(uint8)'r', 0u,(uint8)'o', 0u,
 (uint8)'p', 0u,(uint8)'h', 0u,(uint8)'o', 0u,(uint8)'n', 0u,(uint8)'e', 0u,
/*********************************************************************
* String Descriptor: "Speaker"
*********************************************************************/
/* Descriptor Length                       */ 0x10u,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'S', 0u,(uint8)'p', 0u,(uint8)'e', 0u,(uint8)'a', 0u,(uint8)'k', 0u,
 (uint8)'e', 0u,(uint8)'r', 0u,
/*********************************************************************
* String Descriptor: "USB Streaming"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'U', 0u,(uint8)'S', 0u,(uint8)'B', 0u,(uint8)' ', 0u,(uint8)'S', 0u,
 (uint8)'t', 0u,(uint8)'r', 0u,(uint8)'e', 0u,(uint8)'a', 0u,(uint8)'m', 0u,
 (uint8)'i', 0u,(uint8)'n', 0u,(uint8)'g', 0u,
/*********************************************************************
* String Descriptor: "Active 16 bit"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'A', 0u,(uint8)'c', 0u,(uint8)'t', 0u,(uint8)'i', 0u,(uint8)'v', 0u,
 (uint8)'e', 0u,(uint8)' ', 0u,(uint8)'1', 0u,(uint8)'6', 0u,(uint8)' ', 0u,
 (uint8)'b', 0u,(uint8)'i', 0u,(uint8)'t', 0u,
/*********************************************************************
* String Descriptor: "Active 24 bit"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'A', 0u,(uint8)'c', 0u,(uint8)'t', 0u,(uint8)'i', 0u,(uint8)'v', 0u,
 (uint8)'e', 0u,(uint8)' ', 0u,(uint8)'2', 0u,(uint8)'4', 0u,(uint8)' ', 0u,
 (uint8)'b', 0u,(uint8)'i', 0u,(uint8)'t', 0u,
/*********************************************************************
* String Descriptor: "Mac"
*********************************************************************/
/* Descriptor Length                       */ 0x08u,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'M', 0u,(uint8)'a', 0u,(uint8)'c', 0u,
/*********************************************************************
* String Descriptor: "PlaylistControl"
*********************************************************************/
/* Descriptor Length                       */ 0x20u,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'P', 0u,(uint8)'l', 0u,(uint8)'a', 0u,(uint8)'y', 0u,(uint8)'l', 0u,
 (uint8)'i', 0u,(uint8)'s', 0u,(uint8)'t', 0u,(uint8)'C', 0u,(uint8)'o', 0u,
 (uint8)'n', 0u,(uint8)'t', 0u,(uint8)'r', 0u,(uint8)'o', 0u,(uint8)'l', 0u,
/*********************************************************************
* String Descriptor: "Cypress MFi Digital Audio DVK"
*********************************************************************/
/* Descriptor Length                       */ 0x3Cu,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'C', 0u,(uint8)'y', 0u,(uint8)'p', 0u,(uint8)'r', 0u,(uint8)'e', 0u,
 (uint8)'s', 0u,(uint8)'s', 0u,(uint8)' ', 0u,(uint8)'M', 0u,(uint8)'F', 0u,
 (uint8)'i', 0u,(uint8)' ', 0u,(uint8)'D', 0u,(uint8)'i', 0u,(uint8)'g', 0u,
 (uint8)'i', 0u,(uint8)'t', 0u,(uint8)'a', 0u,(uint8)'l', 0u,(uint8)' ', 0u,
 (uint8)'A', 0u,(uint8)'u', 0u,(uint8)'d', 0u,(uint8)'i', 0u,(uint8)'o', 0u,
 (uint8)' ', 0u,(uint8)'D', 0u,(uint8)'V', 0u,(uint8)'K', 0u,
/*********************************************************************
* String Descriptor: "Audio Control"
*********************************************************************/
/* Descriptor Length                       */ 0x1Cu,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'A', 0u,(uint8)'u', 0u,(uint8)'d', 0u,(uint8)'i', 0u,(uint8)'o', 0u,
 (uint8)' ', 0u,(uint8)'C', 0u,(uint8)'o', 0u,(uint8)'n', 0u,(uint8)'t', 0u,
 (uint8)'r', 0u,(uint8)'o', 0u,(uint8)'l', 0u,
/*********************************************************************
* String Descriptor: "CDC Communication Interface"
*********************************************************************/
/* Descriptor Length                       */ 0x38u,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'C', 0u,(uint8)'D', 0u,(uint8)'C', 0u,(uint8)' ', 0u,(uint8)'C', 0u,
 (uint8)'o', 0u,(uint8)'m', 0u,(uint8)'m', 0u,(uint8)'u', 0u,(uint8)'n', 0u,
 (uint8)'i', 0u,(uint8)'c', 0u,(uint8)'a', 0u,(uint8)'t', 0u,(uint8)'i', 0u,
 (uint8)'o', 0u,(uint8)'n', 0u,(uint8)' ', 0u,(uint8)'I', 0u,(uint8)'n', 0u,
 (uint8)'t', 0u,(uint8)'e', 0u,(uint8)'r', 0u,(uint8)'f', 0u,(uint8)'a', 0u,
 (uint8)'c', 0u,(uint8)'e', 0u,
/*********************************************************************
* String Descriptor: "CDC Data Interface"
*********************************************************************/
/* Descriptor Length                       */ 0x26u,
/* DescriptorType: STRING                  */ 0x03u,
 (uint8)'C', 0u,(uint8)'D', 0u,(uint8)'C', 0u,(uint8)' ', 0u,(uint8)'D', 0u,
 (uint8)'a', 0u,(uint8)'t', 0u,(uint8)'a', 0u,(uint8)' ', 0u,(uint8)'I', 0u,
 (uint8)'n', 0u,(uint8)'t', 0u,(uint8)'e', 0u,(uint8)'r', 0u,(uint8)'f', 0u,
 (uint8)'a', 0u,(uint8)'c', 0u,(uint8)'e', 0u,
/*********************************************************************/
/* Marks the end of the list.              */ 0x00u};
/*********************************************************************/

/*********************************************************************
* Serial Number String Descriptor
*********************************************************************/
const uint8 CYCODE USBFS_SN_STRING_DESCRIPTOR[2] = {
/* Descriptor Length                       */ 0x02u,
/* DescriptorType: STRING                  */ 0x03u
};

/*********************************************************************
* HID Report Descriptor: AudioPlaybackControl
*********************************************************************/
const uint8 CYCODE USBFS_HIDREPORT_DESCRIPTOR1[95u] = {
/*  Descriptor Size (Not part of descriptor)*/ USBFS_HID_RPT_1_SIZE_LSB,
USBFS_HID_RPT_1_SIZE_MSB,
/* USAGE_PAGE                              */ 0x05u, 0x0Cu, 
/* USAGE                                   */ 0x09u, 0x01u, 
/* COLLECTION                              */ 0xA1u, 0x01u, 
/* REPORT_ID                               */ 0x85u, 0x01u, 
/* LOGICAL_MINIMUM                         */ 0x15u, 0x00u, 
/* LOGICAL_MAXIMUM                         */ 0x25u, 0x01u, 
/* REPORT_SIZE                             */ 0x75u, 0x01u, 
/* REPORT_COUNT                            */ 0x95u, 0x03u, 
/* USAGE                                   */ 0x09u, 0xCDu, 
/* USAGE                                   */ 0x09u, 0xB5u, 
/* USAGE                                   */ 0x09u, 0xB6u, 
/* INPUT                                   */ 0x81u, 0x02u, 
/* REPORT_COUNT                            */ 0x95u, 0x05u, 
/* INPUT                                   */ 0x81u, 0x01u, 
/* END_COLLECTION                          */ 0xC0u, 
/* USAGE_PAGE                              */ 0x05u, 0x0Bu, 
/* USAGE                                   */ 0x09u, 0x01u, 
/* COLLECTION                              */ 0xA1u, 0x01u, 
/* REPORT_ID                               */ 0x85u, 0x02u, 
/* LOGICAL_MINIMUM                         */ 0x15u, 0x00u, 
/* LOGICAL_MAXIMUM                         */ 0x25u, 0x01u, 
/* REPORT_SIZE                             */ 0x75u, 0x01u, 
/* REPORT_COUNT                            */ 0x95u, 0x02u, 
/* USAGE                                   */ 0x09u, 0x26u, 
/* USAGE                                   */ 0x09u, 0x2Fu, 
/* INPUT                                   */ 0x81u, 0x02u, 
/* REPORT_COUNT                            */ 0x95u, 0x06u, 
/* INPUT                                   */ 0x81u, 0x01u, 
/* END_COLLECTION                          */ 0xC0u, 
/* USAGE_PAGE                              */ 0x05u, 0x0Bu, 
/* USAGE                                   */ 0x09u, 0x01u, 
/* COLLECTION                              */ 0xA1u, 0x01u, 
/* REPORT_ID                               */ 0x85u, 0x03u, 
/* LOGICAL_MINIMUM                         */ 0x15u, 0x00u, 
/* LOGICAL_MAXIMUM                         */ 0x25u, 0x01u, 
/* REPORT_SIZE                             */ 0x75u, 0x01u, 
/* REPORT_COUNT                            */ 0x95u, 0x08u, 
/* USAGE                                   */ 0x09u, 0x26u, 
/* USAGE                                   */ 0x09u, 0x2Fu, 
/* USAGE                                   */ 0x09u, 0xB0u, 
/* USAGE                                   */ 0x09u, 0xB1u, 
/* USAGE                                   */ 0x09u, 0xB2u, 
/* USAGE                                   */ 0x09u, 0xB3u, 
/* USAGE                                   */ 0x09u, 0xB4u, 
/* USAGE                                   */ 0x09u, 0xB5u, 
/* OUTPUT                                  */ 0x91u, 0x02u, 
/* END_COLLECTION                          */ 0xC0u, 
/*********************************************************************/
/* End of the HID Report Descriptor        */ 0x00u, 0x00u};
/*********************************************************************/

#if !defined(USER_DEFINE_USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_HID_RPT_STORAGE)
/*********************************************************************
* HID Input Report Storage
*********************************************************************/
T_USBFS_XFER_STATUS_BLOCK USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_RPT_SCB_ID1;
uint8 USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_BUF_ID1[
            USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_BUF_SIZE_ID1];

T_USBFS_XFER_STATUS_BLOCK USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_RPT_SCB_ID2;
uint8 USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_BUF_ID2[
            USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_BUF_SIZE_ID2];

/*********************************************************************
* HID Input Report TD Table
*********************************************************************/
const T_USBFS_TD CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_RPT_TABLE[3u] = {
    {NULL,
    NULL,
    NULL},
    {USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_BUF_SIZE_ID1,
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_BUF_ID1[0u],
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_RPT_SCB_ID1},
    {USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_BUF_SIZE_ID2,
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_BUF_ID2[0u],
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_RPT_SCB_ID2},
};
/*********************************************************************
* HID Output Report Storage
*********************************************************************/
T_USBFS_XFER_STATUS_BLOCK USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_OUT_RPT_SCB_ID3;
uint8 USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_OUT_BUF_ID3[
            USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_OUT_BUF_SIZE_ID3];

/*********************************************************************
* HID Output Report TD Table
*********************************************************************/
const T_USBFS_TD CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_OUT_RPT_TABLE[4u] = {
    {NULL,
    NULL,
    NULL},
    {NULL,
    NULL,
    NULL},
    {NULL,
    NULL,
    NULL},
    {USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_OUT_BUF_SIZE_ID3,
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_OUT_BUF_ID3[0u],
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_OUT_RPT_SCB_ID3},
};
/*********************************************************************
* HID Report Look Up Table         This table has four entries:
*                                        IN Report Table
*                                        OUT Report Table
*                                        Feature Report Table
*                                        HID Report Descriptor
*                                        HID Class Descriptor
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_TABLE[5u] = {
    {0x02u,     &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_IN_RPT_TABLE},
    {0x03u,     &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_OUT_RPT_TABLE},
    {0x00u,    NULL},
    {0x01u,     (const void *)&USBFS_HIDREPORT_DESCRIPTOR1[0]},
    {0x01u,     (const void *)&USBFS_DEVICE0_CONFIGURATION0_DESCR[277]}
};
#endif /* USER_DEFINE_USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_HID_RPT_STORAGE */

/*********************************************************************
* Interface Dispatch Table -- Points to the Class Dispatch Tables
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_TABLE[1u] = {
    {USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_COUNT, 
    &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_ALTERNATE0_HID_TABLE}
};
/*********************************************************************
* Endpoint Setting Table -- This table contain the endpoint setting
*                           for each endpoint in the configuration. It
*                           contains the necessary information to
*                           configure the endpoint hardware for each
*                           interface and alternate setting.
*********************************************************************/
const T_USBFS_EP_SETTINGS_BLOCK CYCODE USBFS_DEVICE0_CONFIGURATION0_EP_SETTINGS_TABLE[9u] = {
/* IFC  ALT    EPAddr bmAttr MaxPktSize Class ********************/
{0x00u, 0x00u, 0x83u, 0x03u, 0x0002u,   0x01u},
{0x01u, 0x01u, 0x01u, 0x01u, 0x00C0u,   0x01u},
{0x01u, 0x02u, 0x01u, 0x0Du, 0x0120u,   0x01u},
{0x02u, 0x01u, 0x82u, 0x0Du, 0x0120u,   0x01u},
{0x03u, 0x00u, 0x84u, 0x03u, 0x0002u,   0x03u},
{0x03u, 0x00u, 0x05u, 0x03u, 0x0001u,   0x03u},
{0x04u, 0x00u, 0x86u, 0x03u, 0x0008u,   0x02u},
{0x05u, 0x00u, 0x87u, 0x02u, 0x0040u,   0x0Au},
{0x05u, 0x00u, 0x08u, 0x02u, 0x0040u,   0x0Au}
};
const uint8 CYCODE USBFS_DEVICE0_CONFIGURATION0_INTERFACE_CLASS[6u] = {
0x01u, 0x01u, 0x01u, 0x03u, 0x02u, 0x0Au
};
/*********************************************************************
* Config Dispatch Table -- Points to the Config Descriptor and each of
*                          and endpoint setup table and to each
*                          interface table if it specifies a USB Class
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_DEVICE0_CONFIGURATION0_TABLE[9u] = {
    {0x01u,     &USBFS_DEVICE0_CONFIGURATION0_DESCR},
    {0x09u,     &USBFS_DEVICE0_CONFIGURATION0_EP_SETTINGS_TABLE},
    {0x00u,    NULL},
    {0x00u,    NULL},
    {0x00u,    NULL},
    {0x01u,     &USBFS_DEVICE0_CONFIGURATION0_INTERFACE4_TABLE},
    {0x00u,    NULL},
    {0x00u,    NULL},
    {0x00u,     &USBFS_DEVICE0_CONFIGURATION0_INTERFACE_CLASS}
};
/*********************************************************************
* Device Dispatch Table -- Points to the Device Descriptor and each of
*                          and Configuration Tables for this Device 
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_DEVICE0_TABLE[2u] = {
    {0x01u,     &USBFS_DEVICE0_DESCR},
    {0x01u,     &USBFS_DEVICE0_CONFIGURATION0_TABLE}
};
/*********************************************************************
* Device Table -- Indexed by the device number.
*********************************************************************/
const T_USBFS_LUT CYCODE USBFS_TABLE[1u] = {
    {0x01u,     &USBFS_DEVICE0_TABLE}
};

#endif /* USER_SUPPLIED_DESCRIPTORS */

#if defined(USBFS_ENABLE_MSOS_STRING)

    /******************************************************************************
    *  USB Microsoft OS String Descriptor
    *  "MSFT" identifies a Microsoft host
    *  "100" specifies version 1.00
    *  USBFS_GET_EXTENDED_CONFIG_DESCRIPTOR becomes the bRequest value
    *  in a host vendor device/class request
    ******************************************************************************/

    const uint8 CYCODE USBFS_MSOS_DESCRIPTOR[USBFS_MSOS_DESCRIPTOR_LENGTH] = {
    /* Descriptor Length                       */   0x12u,
    /* DescriptorType: STRING                  */   0x03u,
    /* qwSignature - "MSFT100"                 */   (uint8)'M', 0u, (uint8)'S', 0u, (uint8)'F', 0u, (uint8)'T', 0u,
                                                    (uint8)'1', 0u, (uint8)'0', 0u, (uint8)'0', 0u,
    /* bMS_VendorCode:                         */   USBFS_GET_EXTENDED_CONFIG_DESCRIPTOR,
    /* bPad                                    */   0x00u
    };

    /* Extended Configuration Descriptor */

    const uint8 CYCODE USBFS_MSOS_CONFIGURATION_DESCR[USBFS_MSOS_CONF_DESCR_LENGTH] = {
    /*  Length of the descriptor 4 bytes       */   0x28u, 0x00u, 0x00u, 0x00u,
    /*  Version of the descriptor 2 bytes      */   0x00u, 0x01u,
    /*  wIndex - Fixed:INDEX_CONFIG_DESCRIPTOR */   0x04u, 0x00u,
    /*  bCount - Count of device functions.    */   0x01u,
    /*  Reserved : 7 bytes                     */   0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u,
    /*  bFirstInterfaceNumber                  */   0x00u,
    /*  Reserved                               */   0x01u,
    /*  compatibleID    - "CYUSB\0\0"          */   (uint8)'C', (uint8)'Y', (uint8)'U', (uint8)'S', (uint8)'B',
                                                    0x00u, 0x00u, 0x00u,
    /*  subcompatibleID - "00001\0\0"          */   (uint8)'0', (uint8)'0', (uint8)'0', (uint8)'0', (uint8)'1',
                                                    0x00u, 0x00u, 0x00u,
    /*  Reserved : 6 bytes                     */   0x00u, 0x00u, 0x00u, 0x00u, 0x00u, 0x00u
    };

#endif /* USBFS_ENABLE_MSOS_STRING */

/* DIE ID string descriptor for 8 bytes ID */
#if defined(USBFS_ENABLE_IDSN_STRING)
    uint8 USBFS_idSerialNumberStringDescriptor[USBFS_IDSN_DESCR_LENGTH];
#endif /* USBFS_ENABLE_IDSN_STRING */


/* [] END OF FILE */
